import Head from 'next/head'
import Image from 'next/image'
import {useRouter} from 'next/router'
import Experince from './experince'
import {Container} from '@chakra-ui/react'
import {Box} from '@chakra-ui/react'
import {Heading,Text,Button} from '@chakra-ui/react'
import SKills from '../components/skills'
import React from 'react'
import {FiFolder} from "react-icons/fi"
import {AiFillStar} from "react-icons/ai"
import {TbGitFork} from "react-icons/tb"
import { Grid, GridItem } from '@chakra-ui/react'
import Projects from './Projects'
export default function Home({user,datas})
{
    console.log(user,datas)
    const router=useRouter()
    const follow=() =>
    {
        router.push(`${user.html_url}`)
    }
    const Resume=() =>
    {
        router.push(`${user.blog}`)
    }
    
    return (
        <Container maxW={"90%"}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Box display={'flex'}>
                    <Box w={"25%"} display='grid' p={5}>
                        <Box justifyContent={'center'} alignItems={'center'} p={'2rem 0.5rem'} textAlign={'center'} boxShadow='lg' border={"1px solid lightgray"} borderRadius={'10px'}>
                            <Box borderRadius={'50%'} m={"10px 27%"} bgColor="yellow" width={150} border='2px' height={'auto'} justifyContent={'center'} alignItems={'center'}>
                                <Image src={user.avatar_url} alt="avatar" width={200} height={100} style={{borderRadius: '50%'}} />
                            </Box>
                            <Heading fontSize={28}>{user.name}</Heading>
                            <Text fontWeight={500} color='gray.500'>@{user.login}</Text>
                            <Text>{user.bio.substr(0,80)}</Text>
                            &nbsp;
                            <Box>
                            <Button onClick={Resume} borderRadius={50} m={2} size='lg'p={"1px 30px"} bgColor={"green.300"}>Resume</Button>
                            <Button onClick={follow} borderRadius={50} m={2} size='lg'p={"1px 30px"} bgColor={"blue.300"}>follow</Button>
                            </Box>
                           
                        </Box>
                        <SKills/>
                        <Experince />
                    </Box>  
                        <Projects data={datas.items}/>
                </Box>
            </main>
        </Container>
    )
}

export async function getServerSideProps()
{
    let res=await fetch(`https://api.github.com/users/brar21`)
    let data=await res.json();
    const resp = await fetch(`https://api.github.com/search/repositories?q=user:brar21+fork:true&sort=updated&per_page=10&type=Repositories`);
    let datas = await resp.json();
    return {
        props: {
            user: data,
            datas:datas
        }
    }
}