import React from 'react'
// import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/Home.module.css"
import Link from 'next/link'
import { Heading } from '@chakra-ui/react'
import {Box} from '@chakra-ui/react'
import {Text} from '@chakra-ui/react'
import {FiFolder} from "react-icons/fi"
import {AiFillStar} from "react-icons/ai"
import {TbGitFork} from "react-icons/tb"
import { Grid, GridItem } from '@chakra-ui/react'

const Projects=({data}) =>
{
    console.log(data)
  return (
      <Box className={styles.container}>
          <Head>
              <title>Project Repositries</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
          {/*box-shadow: rgba(0, 0, 0, 0.15) 1.95px 1.95px 2.6px;*/}
              {data && data.map((i) => (
                  <Grid templateColumns='repeat(2, 500px)' gap={6} key={i.id}>
                  <Box key={i.id} textAlign={'start'} m={5} width={'auto'}  border='1px solid lightgray'p={5} borderRadius='10'>
                  <Box>
                  <Heading display={'flex'} alignItems='center' fontSize={15}><FiFolder/>&nbsp;{i.name}</Heading>
                  &nbsp;
                          <Text>{i.description}</Text>
                          &nbsp;
                          <Box display={'flex'} justifyContent='space-between'>
                              <Box display={'flex'}> 
                                  <Text display={'flex'} alignItems='center' color={'yellow.400'}><AiFillStar />&nbsp;{i.stargazers_count}</Text>
                                  &nbsp;
                                  &nbsp;
                                  &nbsp; 
                  <Text display={'flex'} alignItems='center'><TbGitFork/>&nbsp;{ i.forks_count}</Text>
                              </Box>
                              <Box>
                                  <h1>{i.language}</h1>
                              </Box>
                          </Box>
              </Box>
                      </Box>
                      </Grid>
))}
              
          </main>
    </Box>
  )
}

export async function getServerSideProps() {
    // let username = "brar21";
    const res = await fetch(`https://api.github.com/search/repositories?q=user:brar21+fork:true&sort=updated&per_page=10&type=Repositories`);
    let data = await res.json();
    return {
        props:{data:data.items}
    }
}
export default Projects;